import 'package:flutter/material.dart';
import 'package:inzone/email_login.dart';
import 'package:inzone/signup_screens.dart';

class IntroductionScreen extends StatelessWidget {
   const IntroductionScreen({super.key});

  @override
  Widget build(BuildContext context) {
    String licenseAgreement = '''
Introduction
Welcome to InZone operated by InZone Inc. ('we', 'our', 'us'). These Terms and Conditions ('Terms') govern your access to and use of the website located at 'inzone.ai' and the InZone application (collectively the 'Platform'). By using the Platform, you agree to be bound by these Terms. Please read them carefully.

Scope of Services
InZone provides an interactive social media platform that incorporates AI-powered chatbots, 2D/3D avatars, user-generated content, and a Parent Hub for monitoring children’s activities. These services are aimed at promoting healthier content consumption and immersive experiences for users.

Account Creation and Usage
To use our services, you must create an account. During account registration, you agree to provide accurate and up-to-date information. InZone reserves the right to terminate accounts that violate these Terms or contain fraudulent information.

AI Chatbot Interactions
Our Platform includes AI-powered chatbots that allow users to engage with AI-generated content in real-time. These bots simulate conversations with fictional or real-world characters. While they enhance user interaction, the following rules apply: - Purpose: AI chatbots are intended for entertainment and educational use only. Responses from these bots are automated and may not be accurate or appropriate. - Limitation of Liability: InZone is not responsible for any loss, damage, or inconvenience caused by the use of AI chatbot services. AI-generated responses are based on machine learning algorithms and do not undergo human verification. Users should refrain from relying on AI chatbot interactions for personal, legal, or financial decisions. - User Discretion: By engaging with the AI chatbot services, users agree that the content generated by these bots is for general use only and may not be suitable for all contexts. Users should use discretion in sharing sensitive or personal information with AI chatbots.

Intellectual Property
The Platform, including but not limited to AI algorithms, avatars, code, and design elements, is the intellectual property of InZone or its licensors. Unauthorized reproduction, distribution, or use of this content is strictly prohibited.

Parental Monitoring
For users under 13, InZone provides a Parent Hub that enables parents to monitor their child’s activity on the Platform. Although we provide tools to encourage a safe and healthy environment, parents are ultimately responsible for the actions and safety of their children while using InZone.

Sharing of User-Generated Content
Users may share, post, and interact with content created by other users or AI services. All user-generated content must comply with community standards. InZone reserves the right to remove content that violates these standards or is deemed harmful or inappropriate.

Limitation of Liability
In no event shall InZone, its officers, employees, or agents be liable for any indirect, incidental, special, or consequential damages resulting from the use of or inability to use the Platform, including AI chatbot interactions or user-generated content. Users assume all responsibility for their engagement with the Platform.

Dispute Resolution
Any disputes arising under these Terms shall be resolved through binding arbitration in accordance with the rules of [arbitration organization] and by the laws of [State/Country]. You agree to waive your right to participate in any class action lawsuits.

Changes to Terms
InZone reserves the right to update or modify these Terms at any time. Notice of material changes will be provided via email or by posting the updated Terms on the Platform. Your continued use of the Platform after such modifications will constitute your acknowledgment of the modified Terms.

Contact Information
For questions or concerns regarding these Terms, contact: InZone Inc., Riverdale, Maryland 20737 Email: contact@inzone.ai Phone: 240-681-4298

''';


    String privacyPolicy =
        '''
        Introduction
InZone Inc. ('we', 'our', 'us') is committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and protect personal information obtained through our website 'inzone.ai' and the InZone application (collectively the 'Platform'). By using the Platform, you consent to the data practices outlined below.

Information We Collect
We collect two types of information: personally identifiable information and non-personal data. - Personal Information: Includes first and last name, email address, phone number, and your child’s InZone account identifier. We also collect billing and payment information for transactions. - Non-Personal Information: We may collect demographic information, including age, as well as browser details and anonymized data for statistical purposes.

AI Chatbot Data
InZone's AI chatbot services collect conversation data to enhance user experience and improve chatbot performance. Users should be aware that while chatbot conversations are stored for improvement purposes, they should avoid sharing personal or sensitive information during these interactions. - Use of Chatbot Data: Conversation data may be analyzed internally to enhance AI performance. We do not sell or share this data with third parties. - Liability Disclaimer: Users acknowledge that chatbot interactions are for entertainment or educational purposes and InZone is not liable for any advice or information provided by AI bots. Users should not rely on chatbot responses for any critical decisions.

Use of Collected Information
We use the personal information you provide for: - Delivering the services you request - Processing transactions - Communicating with you about updates, offers, or changes to the Platform - Analyzing trends and improving Platform functionality. We do not sell or rent your personal information to third parties.

Children’s Privacy
InZone complies with the Children’s Online Privacy Protection Act (COPPA). We collect personal information from children under 13 only for the purpose of providing parental monitoring services through the Parent Hub. Parental consent is required for any data collection involving children. - Parental Control: Parents can control their child’s interactions on InZone through the Parent Hub. Any collected data is for monitoring purposes and is not shared externally.

Data Security
We implement industry-standard security measures, including HTTPS and database isolation, to protect your personal information. However, we cannot guarantee complete security due to the inherent risks of data transmission over the Internet.

Right to Deletion
You have the right to request the deletion of your personal data. We will comply with all deletion requests subject to legal exceptions such as complying with regulatory obligations or preventing fraudulent activity.

Retention of Data
We retain personal information only as long as necessary to fulfill the purposes for which it was collected or to comply with legal obligations. Data related to AI chatbots is anonymized and used to improve functionality.

Changes to this Policy
InZone may update this Privacy Policy periodically. We will notify you of significant changes through email or by posting a notice on the Platform.

Contact Information
For any questions or concerns regarding this Privacy Policy, please contact us: InZone Inc., Riverdale, Maryland 20737 Email: contact@inzone.ai Phone: 240-681-4298
        ''';
    return Scaffold(
      backgroundColor: Colors.black,
        body: SafeArea(
          left: false,
          right: false,
          top: false,
          bottom: false,
          child: Stack(  clipBehavior: Clip.none,
              children: [
                Positioned.fill(
                  child: Container(
                    padding: EdgeInsets.zero,
                    margin: EdgeInsets.zero,
                    child: Transform.scale(
                      scale: 1.008, // Scale the image by 1.2 times
                      child: Image.asset(
                        "assets/images/intropic.png",
                        fit: BoxFit.cover,
                      ),
                    ),
                  ),
                ),

                 Align(
          alignment: Alignment.bottomCenter,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 30, ),
                child: Container(
                  height: MediaQuery.of(context).size.height * 0.07,
                  width: MediaQuery.of(context).size.width,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15),
                    color: Theme.of(context).canvasColor.withOpacity(0.9),

                    boxShadow: [
                      BoxShadow(
                        color: Colors.black12.withOpacity(0.05),
                        spreadRadius: 1,
                        blurRadius: 7,
                        offset: const Offset(0, -1),
                      ),
                    ],
                  ),
                  child: Padding(
                    padding: const EdgeInsets.only(right: 5),
                    child: Row(
                      children: [
                        GestureDetector(
                          onTap: () {
                            Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: ((context) =>  const SignUpScreens())));
                          },
                          child: Container(
                            height: MediaQuery.of(context).size.height * 0.08,
                            width: MediaQuery.of(context).size.width / 2.2,
                            decoration: BoxDecoration(
                              color: Theme.of(context).colorScheme.primary,
                              borderRadius: BorderRadius.circular(15),
                            ),
                            child: Center(
                              child: Text(
                                "Register",
                                style: Theme.of(context).textTheme.titleMedium,
                              ),
                            ),
                          ),
                        ),
                        const Spacer(),
                        GestureDetector(
                          onTap: () {
                            Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: ((context) =>   const EmailLogInPage())));

                          },
                          child: Text(
                            "Sign In",
                            style: Theme.of(context).textTheme.titleMedium,
                          ),
                        ),
                        const Spacer(),
                      ],
                    ),
                  ),
                ),
              ),
              Flexible(child: Padding(
                padding: const EdgeInsets.only(top: 10.0, bottom: 30),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                  TextButton(onPressed: (){
                    showDialog(
                      context: context,
                      builder: (context) {
                        return AlertDialog(
                            actions: [
                              TextButton(
                                  onPressed: () {
                                    Navigator.pop(context);
                                  },
                                  child: const Text("Close"))
                            ],
                            content: SingleChildScrollView(
                              child: Text(licenseAgreement),
                            ));
                      },
                    );
                  }, child:  Text("Terms", style: Theme.of(context).textTheme.bodySmall!.copyWith(color: Colors.white,  ),)),
                    TextButton(onPressed: (){
                      showDialog(
                        context: context,
                        builder: (context) {
                          return AlertDialog(
                              actions: [
                                TextButton(
                                    onPressed: () {
                                      Navigator.pop(context);
                                    },
                                    child: const Text("Close"))
                              ],
                              content: SingleChildScrollView(
                                child: Text(privacyPolicy),
                              ));
                        },
                      );
                    }, child:  Text("Privacy", style: Theme.of(context).textTheme.bodySmall!.copyWith(color: Colors.white, ),)),
               ],),
              ))
            ],
          ),
                ),
              ]),
        ));
  }
}
